### ISSUE TITLE
Max retries exceeded

### ISSUE THREAD

**Issue by jkariscodes** [gthaka/gthaka#1]
Some issues in fetching content. Saya max retries exceeded. Many have the same issue. It is referenced [here](https://github.com/anuraghazra/github-readme-stats/issues/1759)
![image](https://user-images.githubusercontent.com/23359514/168976576-67d40df5-4794-405b-8486-e170c3b7863e.png)

**Comment by gthaka** [comment]
Thanks. 
I saw the issue is being discussed on [#1471](https://github.com/anuraghazra/github-readme-stats/issues/1471)
